name: Atualizar e Deployar Feed RSS

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Executar script para gerar XML
        run: python generate_rss.py

      - name: Deploy no Cloudflare Pages
        uses: cloudflare/wrangler-action@v3.4.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'noticias-ia'
          directory: '.'
