name: Atualizar e Deployar Feed RSS
on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 6'   # Sábados às 09h UTC (06h UTC-3)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
        
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Instalar dependências
        run: pip install requests
        
      - name: Executar script para gerar XML
        run: python generate_rss.py
        
      - name: Fazer commit e push das alterações
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions-bot@github.com"
          git add index.xml
          git diff --staged --quiet || git commit -m "chore: Atualiza o feed de notícias RSS semanal"
          git push